# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Update NuGet package

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    
defaults:
  run:
    working-directory: ./TimeLogging.Grpc

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        source-url: https://nuget.pkg.github.com/czprz/index.json
        dotnet-version: 7.0.x
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Publish
      run: dotnet nuget push "bin/Release/TimeLogging.Interfaces.*.nupkg" --skip-duplicate
